### ISSUE TITLE
The shortcut did not copy text to clipboard

### ISSUE THREAD

**Issue by 9amcoder** [e-kotov/macos-shortcuts#2]
`mac Sonoma Version 14.6.1 (23G93)`
I've installed the shortcut and try it to capture an text content; however, the shortcut cannot get text directly and it return picture when I paste it.

The intended behaviour should be clipboard can paste text string format after use the shortcut.

<img width="590" alt="Screenshot 2024-09-08 at 9 14 00 PM" src="https://github.com/user-attachments/assets/56d92b2c-11c5-4fe4-87ad-77d46844d78e">

**Comment by 9amcoder** [comment]
It seems like my system's problem, after reboot (restarted) the computer, it worked fine.

**Comment by e-kotov** [comment]
@9amcoder I'm glad it's solved for you.
